OVERRIDES = {
    # === Existing Entries ===
    "fundrise income real estate fund": "Fundrise Income Real Estate Fund, LLC",
    "fundrise income fund": "Fundrise Income Fund, LLC",
    "morgan stanley domestic holdings": "Morgan Stanley Domestic Holdings, Inc",
    "morgan stanley domestic holding": "Morgan Stanley Domestic Holdings, Inc",
    "morgan stanley holdings inc": "Morgan Stanley Domestic Holdings, Inc",
    "morgan stanley holdings": "Morgan Stanley Domestic Holdings, Inc",

    # === Major Brokerages & Investment Platforms ===
    "charles schwab": "Charles Schwab",
    "fidelity": "Fidelity Investments",
    "vanguard": "Vanguard",
    "etrade": "E*TRADE (Morgan Stanley)",
    "td ameritrade": "TD Ameritrade (Charles Schwab)",
    "merrill": "Merrill (Bank of America)",
    "robinhood": "Robinhood",
    "webull": "Webull",
    "public.com": "Public.com",
    "interactive brokers": "Interactive Brokers",
    "sofi invest": "SoFi Invest",
    "betterment": "Betterment",
    "wealthfront": "Wealthfront",
    "acorns": "Acorns",
    "ally invest": "Ally Invest",
    "stash": "Stash",
    "m1 finance": "M1 Finance",
    "firstrade": "Firstrade",
    "tradestation": "TradeStation",
    "apex clearing": "Apex Clearing",
    "raymond james": "Raymond James",
    "lpl financial": "LPL Financial",
    "edward jones": "Edward Jones",
    "stifel": "Stifel Financial",
    "pershing": "Pershing LLC",
    "tastytrade": "Tastytrade",
    "jp morgan self-directed": "J.P. Morgan Self-Directed Investing",
    "morgan stanley wealth": "Morgan Stanley Wealth Management",
    "schwab intelligent portfolios": "Charles Schwab Intelligent Portfolios",

    # === Banks / Financial Firms with Investment Products ===
    "jpmorgan chase": "JPMorgan Chase Bank",
    "bank of america": "Bank of America",
    "wells fargo advisors": "Wells Fargo Advisors",
    "citibank wealth": "Citibank Wealth Management",
    "u.s. bank": "US Bank Investments",
    "us bank": "US Bank Investments",
    "pnc investments": "PNC Investments",
    "truist investments": "Truist Investments",
    "capital one investing": "Capital One Investing",
    "regions investment": "Regions Investment Services",
    "fifth third securities": "Fifth Third Securities",
    "hsbc securities": "HSBC Securities (USA)",
    "ubs": "UBS Financial Services",
    "bmo harris": "BMO Harris Financial Advisors",
    "comerica securities": "Comerica Securities",

    # === Mutual Fund & ETF Families ===
    "t rowe price": "T. Rowe Price",
    "franklin templeton": "Franklin Templeton",
    "american funds": "American Funds (Capital Group)",
    "blackrock": "BlackRock",
    "ishares": "BlackRock iShares",
    "invesco": "Invesco",
    "jpmorgan funds": "J.P. Morgan Funds",
    "state street": "State Street Global Advisors (SPDR)",
    "spdr": "State Street SPDR ETFs",
    "charles schwab funds": "Charles Schwab Funds",
    "dfa": "Dimensional Fund Advisors (DFA)",
    "dimensional fund": "Dimensional Fund Advisors (DFA)",
    "janus henderson": "Janus Henderson Investors",
    "nuveen": "Nuveen Investments",
    "eaton vance": "Eaton Vance",
    "oppenheimer": "OppenheimerFunds (Invesco)",
    "lord abbett": "Lord Abbett",
    "columbia threadneedle": "Columbia Threadneedle Investments",
    "principal funds": "Principal Funds",
    "american century": "American Century Investments",
    "putnam": "Putnam Investments",
    "john hancock": "John Hancock Funds",
    "hartford funds": "Hartford Funds",
    "mfs": "MFS Investment Management",
    "goldman sachs funds": "Goldman Sachs Funds",
    "morgan stanley funds": "Morgan Stanley Funds",
    "northern funds": "Northern Funds",
    "tiaa": "TIAA Investments",
    "bny mellon": "BNY Mellon Investment Management",

    # === REITs, BDCs, and Dividend Trusts ===
    "realty income": "Realty Income Corporation",
    "simon property": "Simon Property Group",
    "prologis": "Prologis Inc.",
    "digital realty": "Digital Realty Trust",
    "crown castle": "Crown Castle Inc.",
    "american tower": "American Tower Corporation",
    "annaly capital": "Annaly Capital Management",
    "agnc investment": "AGNC Investment Corp.",
    "main street capital": "Main Street Capital Corp.",
    "ares capital": "Ares Capital Corp.",
    "hercules capital": "Hercules Capital Inc.",
    "gladstone capital": "Gladstone Capital Corp.",
    "starwood property": "Starwood Property Trust",
    "blackstone real estate": "Blackstone Real Estate Income Trust",
    "enterprise products": "Enterprise Products Partners L.P.",
    "energy transfer": "Energy Transfer LP",
    "kinder morgan": "Kinder Morgan Inc.",
    "enbridge": "Enbridge Inc.",
    "oneok": "ONEOK Inc.",
    "brookfield infrastructure": "Brookfield Infrastructure Partners",
    "brookfield renewable": "Brookfield Renewable Partners",

    # === Common Dividend-Paying Public Companies ===
    "at&t": "AT&T Inc.",
    "verizon": "Verizon Communications Inc.",
    "apple": "Apple Inc.",
    "microsoft": "Microsoft Corporation",
    "coca cola": "The Coca-Cola Company",
    "pepsico": "PepsiCo Inc.",
    "exxon mobil": "Exxon Mobil Corporation",
    "chevron": "Chevron Corporation",
    "johnson & johnson": "Johnson & Johnson",
    "procter & gamble": "Procter & Gamble Co.",
    "pfizer": "Pfizer Inc.",
    "mcdonald": "McDonald’s Corporation",
    "intel": "Intel Corporation",
    "ibm": "IBM Corporation",
    "walmart": "Walmart Inc.",
    "home depot": "The Home Depot, Inc.",
    "3m": "3M Company",
    "abbvie": "AbbVie Inc.",
    "caterpillar": "Caterpillar Inc.",
    "lockheed martin": "Lockheed Martin Corporation",
}
